[en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    [en.pagination]
        disableAliases = false
        pagerSize = 100
        path = 'page'
    [en.taxonomies]
        author = 'author'
        category = 'categories'
        series = 'series'
        tag = 'tags'

[id]
    contentDir = 'content/id'
    disabled = true
    languageCode = 'id-ID'
    languageDirection = 'ltr'
    languageName = 'Bahasa Indonesia'
    [id.pagination]
        disableAliases = false
        pagerSize = 100
        path = 'laman'
    [id.params.feed]
        flowlines = false

[it]
    contentDir = 'content/it'
    disabled = true
    languageCode = 'it-IT'
    languageDirection = 'ltr'
    languageName = 'Italian'